// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLaundry.Models;

#nullable disable

namespace MiniLaundry.Migrations
{
    [DbContext(typeof(DBHelper))]
    [Migration("20260127004610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniLaundry.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kiloan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meteran"
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Batang",
                            Name = "Alok",
                            PhoneNum = "+6256488976532"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pekalongan",
                            Name = "Bowo",
                            PhoneNum = "+6287655387653"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tegal",
                            Name = "Budiono",
                            PhoneNum = "+6280766498076"
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.DetailPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("TotalUnitService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DetailPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackageId = 1,
                            ServiceId = 1,
                            TotalUnitService = 1
                        },
                        new
                        {
                            Id = 2,
                            PackageId = 1,
                            ServiceId = 2,
                            TotalUnitService = 2
                        },
                        new
                        {
                            Id = 3,
                            PackageId = 1,
                            ServiceId = 5,
                            TotalUnitService = 2
                        },
                        new
                        {
                            Id = 4,
                            PackageId = 2,
                            ServiceId = 3,
                            TotalUnitService = 3
                        },
                        new
                        {
                            Id = 5,
                            PackageId = 2,
                            ServiceId = 4,
                            TotalUnitService = 3
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.DetailTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeaderTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<float>("TotalUnit")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HeaderTransactionId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("DetailTransactions");
                });

            modelBuilder.Entity("MiniLaundry.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bumi",
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@penatu.id",
                            JobId = 1,
                            Name = "Admin",
                            Password = "p4s?",
                            PhoneNum = "+6289988776655",
                            Salary = 3000000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mars",
                            DateOfBirth = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hartono09@gmail.com",
                            JobId = 2,
                            Name = "Hartono",
                            Password = "p4s?",
                            PhoneNum = "+62876533876532",
                            Salary = 2500000m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ds. Klewer, Kec. Tulis",
                            DateOfBirth = new DateTime(2002, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ubed25@gmail.com",
                            JobId = 3,
                            Name = "Ubed",
                            Password = "p4s?",
                            PhoneNum = "+6286544987320",
                            Salary = 2500000m
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ds. Sengon, Kec. Subah",
                            DateOfBirth = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "komar@gmail.com",
                            JobId = 4,
                            Name = "Komar",
                            Password = "p4s?",
                            PhoneNum = "+6289267530098",
                            Salary = 2500000m
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.HeaderTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompleteEstDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("HeaderTransactions");
                });

            modelBuilder.Entity("MiniLaundry.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pencuci"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Penyetrika"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kurir"
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Paket untuk hari raya",
                            Duration = 14,
                            Name = "Paket Hari Raya",
                            Price = 100000
                        },
                        new
                        {
                            Id = 2,
                            Description = "Paket yang mendekati kecepatan cahaya",
                            Duration = 6,
                            Name = "Paket Kilat",
                            Price = 150000
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EstimationDuration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            EstimationDuration = 4,
                            Name = "Cuci Kiloan",
                            Price = 20000,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            EstimationDuration = 6,
                            Name = "Cuci Setrika",
                            Price = 30000,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            EstimationDuration = 1,
                            Name = "Cuci Kilat",
                            Price = 30000,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            EstimationDuration = 1,
                            Name = "Setrika Kilat",
                            Price = 20000,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            EstimationDuration = 2,
                            Name = "Cuci Korden",
                            Price = 10000,
                            UnitId = 2
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "m"
                        });
                });

            modelBuilder.Entity("MiniLaundry.Models.DetailPackage", b =>
                {
                    b.HasOne("MiniLaundry.Models.Package", "Package")
                        .WithMany("detailPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLaundry.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MiniLaundry.Models.DetailTransaction", b =>
                {
                    b.HasOne("MiniLaundry.Models.HeaderTransaction", "HeaderTransaction")
                        .WithMany("DetailTransactions")
                        .HasForeignKey("HeaderTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLaundry.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("MiniLaundry.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("HeaderTransaction");

                    b.Navigation("Package");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MiniLaundry.Models.Employee", b =>
                {
                    b.HasOne("MiniLaundry.Models.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MiniLaundry.Models.HeaderTransaction", b =>
                {
                    b.HasOne("MiniLaundry.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLaundry.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MiniLaundry.Models.Service", b =>
                {
                    b.HasOne("MiniLaundry.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLaundry.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MiniLaundry.Models.HeaderTransaction", b =>
                {
                    b.Navigation("DetailTransactions");
                });

            modelBuilder.Entity("MiniLaundry.Models.Job", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MiniLaundry.Models.Package", b =>
                {
                    b.Navigation("detailPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
